services:
  encurtador:
    build:
      context: ./backend
      dockerfile: "./dockerfiles/encurtador.dockerfile"
      args:
        - USER_ID=1000
        - GROUP_ID=1000
    ports:
      - 3000:3000
    volumes:
      - "./backend/:/app"
    env_file:
      - ./backend/env/encurtador.env
      - ./backend/env/postgres.env
    command: ["start"]
  postgres:
    image: "postgres:17"
    env_file:
      - ./backend/env/postgres.env
    ports:
      - 5432:5432
    volumes:
      - encurtador_pgdata:/var/lib/postgresql/data
volumes:
  encurtador_pgdata:
    